// flow-typed signature: 3ef1b396cb839debce6d597e8ccc4287
// flow-typed version: <<STUB>>/data-attrs-to-js_v^1.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'data-attrs-to-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'data-attrs-to-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'data-attrs-to-js/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'data-attrs-to-js/index' {
  declare module.exports: $Exports<'data-attrs-to-js'>;
}
declare module 'data-attrs-to-js/index.js' {
  declare module.exports: $Exports<'data-attrs-to-js'>;
}
declare module 'data-attrs-to-js/test.js' {
  declare module.exports: $Exports<'data-attrs-to-js/test'>;
}
