// flow-typed signature: 07fd63647e446373a979a4b7eb57f2a8
// flow-typed version: <<STUB>>/get-element-center_v^1.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-element-center'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-element-center' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-element-center/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'get-element-center/index' {
  declare module.exports: $Exports<'get-element-center'>;
}
declare module 'get-element-center/index.js' {
  declare module.exports: $Exports<'get-element-center'>;
}
declare module 'get-element-center/test/test.js' {
  declare module.exports: $Exports<'get-element-center/test/test'>;
}
