// flow-typed signature: af9a603b322a92c86dae6cb671d77989
// flow-typed version: <<STUB>>/image-promise_v^5.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'image-promise/dist/image-promise.common-js' {
  declare module.exports: any;
}

declare module 'image-promise/dist/image-promise.es-modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'image-promise/dist/image-promise.common-js.js' {
  declare module.exports: $Exports<'image-promise/dist/image-promise.common-js'>;
}
declare module 'image-promise/dist/image-promise.es-modules.js' {
  declare module.exports: $Exports<'image-promise/dist/image-promise.es-modules'>;
}
