// flow-typed signature: d401c071ea00147eebc87c211ac671f8
// flow-typed version: <<STUB>>/is-firefox_v^1.0.3/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-firefox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-firefox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-firefox/index' {
  declare module.exports: $Exports<'is-firefox'>;
}
declare module 'is-firefox/index.js' {
  declare module.exports: $Exports<'is-firefox'>;
}
