// flow-typed signature: 383330296f0b26978156c7a370b818be
// flow-typed version: <<STUB>>/object.defaults_v^1.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object.defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object.defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object.defaults/immutable' {
  declare module.exports: any;
}

declare module 'object.defaults/mutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object.defaults/immutable.js' {
  declare module.exports: $Exports<'object.defaults/immutable'>;
}
declare module 'object.defaults/index' {
  declare module.exports: $Exports<'object.defaults'>;
}
declare module 'object.defaults/index.js' {
  declare module.exports: $Exports<'object.defaults'>;
}
declare module 'object.defaults/mutable.js' {
  declare module.exports: $Exports<'object.defaults/mutable'>;
}
