// flow-typed signature: 57a07c2dc935ea96ab64c6d7bc10d001
// flow-typed version: <<STUB>>/queryselectorall_v^0.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'queryselectorall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'queryselectorall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'queryselectorall/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'queryselectorall/index' {
  declare module.exports: $Exports<'queryselectorall'>;
}
declare module 'queryselectorall/index.js' {
  declare module.exports: $Exports<'queryselectorall'>;
}
declare module 'queryselectorall/test.js' {
  declare module.exports: $Exports<'queryselectorall/test'>;
}
