// flow-typed signature: ddfb81ff7de8ec8a784a3c4c556d1c3a
// flow-typed version: <<STUB>>/rollup-plugin-browsersync_v^0.2.5/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-browsersync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-browsersync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-browsersync/test/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-browsersync/test/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-browsersync/index' {
  declare module.exports: $Exports<'rollup-plugin-browsersync'>;
}
declare module 'rollup-plugin-browsersync/index.js' {
  declare module.exports: $Exports<'rollup-plugin-browsersync'>;
}
declare module 'rollup-plugin-browsersync/test/index.js' {
  declare module.exports: $Exports<'rollup-plugin-browsersync/test/index'>;
}
declare module 'rollup-plugin-browsersync/test/rollup.config.js' {
  declare module.exports: $Exports<'rollup-plugin-browsersync/test/rollup.config'>;
}
